### ISSUE TITLE
the dataset is too large

### ISSUE THREAD

**Issue by rebornwwp** [moabitcoin/Adversarial-video-summarization-pytorch#2]
Hi,
I want to train this model now, But I found the dataset is too large (1.8TB), where can I get the data with several GB?

**Comment by EmnamoR** [comment]
in the download section https://bdd-data.berkeley.edu/portal.html. you can download  video parts.
<img width="912" alt="Screenshot 2019-12-16 at 19 06 19" src="https://user-images.githubusercontent.com/23196931/70931241-491aba80-2037-11ea-9add-da08a7d29cc0.png">

**Comment by rebornwwp** [comment]
Thanks, I will have a try.
